version: "3"

services:
  # frontend:
  #   build: ./frontend/
  #   volumes:
  #     - "./frontend/:/app/"
  #   ports:
  #     - '3001:3000'
  #   depends_on:
  #     - backend


  backend:
    build: ./backend/
    volumes:
      - "./backend/app:/app" 
    ports:
      - '5000:5000'
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: redis
    command: redis-server --save 20 1
    ports:
      - '6381:6379'
    volumes:
    - "./redis_db:/data"
